# Generated by Django 5.2.17 on 2026-08-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60)),
                ('emp_id', models.IntegerField(blank=True, null=True)),
                ('nonemp_id', models.IntegerField(blank=True, null=True)),
                ('dept_id', models.IntegerField()),
                ('user_login_id', models.CharField(max_length=20, unique=True)),
                ('user_active', models.CharField(default='Y', max_length=1)),
                ('user_type_id', models.CharField(max_length=1)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('user_from', models.DateField()),
                ('user_to', models.DateField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=40, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_user',
            },
        ),
        migrations.CreateModel(
            name='MstUserPassword',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='password_row', serialize=False, to='core.mstuser')),
                ('password_hash', models.CharField(max_length=64)),
                ('set_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_user_password',
            },
        ),
    ]
