# Generated by Django 5.2.17 on 2026-08-20 06:58

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(max_length=60, unique=True)),
                ('menu_label', models.CharField(max_length=60)),
                ('menu_group', models.CharField(blank=True, max_length=40)),
                ('group_order', models.SmallIntegerField(default=0)),
                ('menu_order', models.SmallIntegerField(default=0)),
                ('view_available', models.BooleanField(default=True)),
                ('add_available', models.BooleanField(default=False)),
                ('edit_available', models.BooleanField(default=False)),
                ('delete_available', models.BooleanField(default=False)),
                ('export_available', models.BooleanField(default=False)),
                ('upload_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('cr_dt', models.DateTimeField(auto_now_add=True)),
                ('mod_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_menu',
                'ordering': ['group_order', 'menu_order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_login_id', models.CharField(db_index=True, max_length=20)),
                ('is_app_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_user_profile',
            },
        ),
        migrations.AlterField(
            model_name='mstuser',
            name='dept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SysAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(max_length=50)),
                ('action', models.CharField(db_index=True, max_length=24)),
                ('entity', models.CharField(db_index=True, max_length=60)),
                ('entity_label', models.CharField(blank=True, max_length=80)),
                ('record_id', models.CharField(blank=True, max_length=40)),
                ('record_label', models.CharField(blank=True, max_length=200)),
                ('changes', core.fields.PortableJSONField(blank=True, default=None, null=True)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'sys_audit_log',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['entity', 'ts'], name='sys_audit_l_entity_9d1c54_idx'), models.Index(fields=['user_id', 'ts'], name='sys_audit_l_user_id_8dbea0_idx'), models.Index(fields=['action', 'ts'], name='sys_audit_l_action_d2ac61_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('menu_key', models.CharField(max_length=60)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('granted_by', models.CharField(blank=True, max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_user_permissions',
                'unique_together': {('user_id', 'menu_key')},
            },
        ),
    ]
