# Generated by Django 5.2.17 on 2026-08-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sysmenu_userprofile_alter_mstuser_dept_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstDepartment',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_dispname', models.CharField(max_length=25)),
                ('dept_abrv', models.CharField(max_length=8)),
                ('dept_order', models.IntegerField(default=0)),
                ('dept_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_department',
                'ordering': ['dept_order'],
            },
        ),
        migrations.RemoveField(
            model_name='mstuser',
            name='dept_id',
        ),
        migrations.AddField(
            model_name='mstuser',
            name='department',
            field=models.ForeignKey(blank=True, db_column='dept_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.mstdepartment'),
        ),
    ]
