# Generated by Django 5.2.17 on 2026-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mstdepartment_remove_mstuser_dept_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstuser',
            name='user_login_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
