# Generated by Django 5.2.17 on 2026-08-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mstuser_user_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstCertInstitute',
            fields=[
                ('cert_institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_institute_name', models.CharField(max_length=100)),
                ('cert_institute_shortname', models.CharField(max_length=10)),
                ('cert_institute_address', models.CharField(blank=True, max_length=100, null=True)),
                ('location_id', models.IntegerField()),
                ('tel_no', models.CharField(blank=True, max_length=15, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_cert_institute',
            },
        ),
        migrations.CreateModel(
            name='MstContractor',
            fields=[
                ('contractor_id', models.AutoField(primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(max_length=40)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_contractor',
            },
        ),
        migrations.CreateModel(
            name='MstCostCentreType',
            fields=[
                ('cost_centre_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_centre_type_name', models.CharField(max_length=15)),
                ('cost_centre_type_shortname', models.CharField(max_length=10)),
                ('cost_centre_type_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_cost_centre_type',
            },
        ),
        migrations.CreateModel(
            name='MstEmailNotificationType',
            fields=[
                ('en_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('en_type_name', models.CharField(max_length=50)),
                ('en_type_subject', models.CharField(max_length=100)),
                ('en_description', models.TextField()),
                ('en_type_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_email_notification_type',
            },
        ),
        migrations.CreateModel(
            name='MstOperator',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=60)),
                ('operator_short_name', models.CharField(max_length=15)),
                ('operator_sap_code', models.CharField(blank=True, max_length=8, null=True)),
                ('wbs_client_code', models.CharField(blank=True, max_length=4, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=75, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=12, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=40, null=True)),
                ('operator_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_operator',
            },
        ),
        migrations.CreateModel(
            name='MstRig',
            fields=[
                ('rig_id', models.AutoField(primary_key=True, serialize=False)),
                ('rig_name', models.CharField(max_length=40)),
                ('rig_short_name', models.CharField(max_length=8)),
                ('old_rig_name', models.CharField(blank=True, max_length=40, null=True)),
                ('rig_subtype_id', models.IntegerField()),
                ('rig_type_id', models.IntegerField()),
                ('rig_built_dt', models.DateField()),
                ('rig_tel_no', models.CharField(blank=True, max_length=25, null=True)),
                ('rig_fax_no', models.CharField(blank=True, max_length=15, null=True)),
                ('rig_email_id', models.EmailField(blank=True, max_length=50, null=True)),
                ('personnel_area', models.CharField(blank=True, max_length=10, null=True)),
                ('org_unit_code', models.CharField(blank=True, max_length=10, null=True)),
                ('rig_from', models.DateField()),
                ('rig_to', models.DateField(blank=True, null=True)),
                ('rig_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_rig',
            },
        ),
        migrations.CreateModel(
            name='MstCostCentre',
            fields=[
                ('cost_centre_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_centre_name', models.CharField(max_length=50)),
                ('old_cost_centre_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fs_emp_id', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('cost_centre_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('cost_centre_type', models.ForeignKey(blank=True, db_column='cost_centre_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centres', to='core.mstcostcentretype')),
                ('rig', models.ForeignKey(blank=True, db_column='rig_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centres', to='core.mstrig')),
            ],
            options={
                'db_table': 'mst_cost_centre',
            },
        ),
    ]
