# Generated by Django 5.2.17 on 2026-08-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mstcertinstitute_mstcontractor_mstcostcentretype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstcostcentre',
            name='cost_centre_type',
            field=models.ForeignKey(blank=True, db_column='cost_centre_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centres', to='core.mstcostcentretype'),
        ),
        migrations.AlterField(
            model_name='mstcostcentre',
            name='rig',
            field=models.ForeignKey(blank=True, db_column='rig_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centres', to='core.mstrig'),
        ),
    ]
