# Generated by Django 5.2.17 on 2026-08-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mstcostcentre_cost_centre_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstCompetency',
            fields=[
                ('competency_id', models.AutoField(primary_key=True, serialize=False)),
                ('competency_name', models.CharField(max_length=50)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.PROTECT, related_name='competencies', to='core.mstdepartment')),
            ],
            options={
                'db_table': 'mst_competency',
            },
        ),
    ]
