# Generated by Django 5.2.17 on 2026-08-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mstcompetency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstFsCategory',
            fields=[
                ('fs_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('fs_category_name', models.CharField(max_length=25)),
                ('business_system_id_2', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_5', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_6', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_11', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_16', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_fs_category',
            },
        ),
        migrations.CreateModel(
            name='MstRank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('vessel_dept_id', models.IntegerField()),
                ('rank_name', models.CharField(max_length=35)),
                ('rank_abrv', models.CharField(max_length=7)),
                ('rank_order', models.IntegerField(default=0)),
                ('business_system_id_2', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_5', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_6', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_11', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='ranks', to='core.mstfscategory')),
            ],
            options={
                'db_table': 'mst_rank',
                'ordering': ['rank_order'],
            },
        ),
    ]
