# Generated by Django 5.2.17 on 2026-08-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mstfscategory_mstrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescriptionHdr',
            fields=[
                ('jd_hdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('jd_hdr_description', models.CharField(max_length=75)),
                ('jd_hdr_order', models.IntegerField(default=0)),
                ('jd_hdr_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstfscategory')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='jd_headers', to='core.mstrank')),
            ],
            options={
                'db_table': 'job_description_hdr',
                'ordering': ['jd_hdr_order'],
            },
        ),
        migrations.CreateModel(
            name='JobDescriptionDtl',
            fields=[
                ('jd_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('jd_dtl_description', models.CharField(max_length=500)),
                ('jd_dtl_order', models.IntegerField(default=0)),
                ('jd_dtl_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('header', models.ForeignKey(db_column='jd_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.jobdescriptionhdr')),
            ],
            options={
                'db_table': 'job_description_dtl',
                'ordering': ['jd_dtl_order'],
            },
        ),
    ]
