# Generated by Django 5.2.17 on 2026-08-20 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobdescriptionhdr_jobdescriptiondtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelEligibility',
            fields=[
                ('travel_eligibility_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_mode', models.CharField(choices=[('A', 'Air'), ('R', 'Rail'), ('C', 'Coach')], max_length=1)),
                ('travel_class', models.CharField(max_length=225)),
                ('travel_preference', models.IntegerField(default=1)),
                ('eligible_from', models.DateField()),
                ('eligible_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstfscategory')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstrank')),
            ],
            options={
                'db_table': 'travel_eligibility',
            },
        ),
    ]
