# Generated by Django 5.2.17 on 2026-08-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_traveleligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingStructure',
            fields=[
                ('reporting_structure_id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstfscategory')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstrank')),
                ('reporting_rank', models.ForeignKey(blank=True, db_column='reporting_rank_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstrank')),
            ],
            options={
                'db_table': 'reporting_structure',
            },
        ),
    ]
