# Generated by Django 5.2.17 on 2026-08-20 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reportingstructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstContactExposureType',
            fields=[
                ('contact_expo_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_expo_type_name', models.CharField(max_length=65)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_contact_exposure_type',
            },
        ),
        migrations.CreateModel(
            name='MstHazardType',
            fields=[
                ('haz_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('haz_type_name', models.CharField(max_length=25)),
                ('haz_type_class', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('haz_type_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_hazard_type',
            },
        ),
        migrations.CreateModel(
            name='MstHseActivity',
            fields=[
                ('hse_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('hse_activity_name', models.CharField(max_length=50)),
                ('hse_activity_type', models.CharField(choices=[('IN', 'Inspection'), ('DR', 'Drill'), ('AU', 'Audit'), ('OT', 'Other')], max_length=2)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_hse_activity',
            },
        ),
        migrations.CreateModel(
            name='MstHseConsumable',
            fields=[
                ('hse_consumable_id', models.AutoField(primary_key=True, serialize=False)),
                ('hse_consumable_name', models.CharField(max_length=100)),
                ('hse_consumption_unit', models.CharField(max_length=15)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_hse_consumable',
            },
        ),
        migrations.CreateModel(
            name='MstIndicatorType',
            fields=[
                ('indicator_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_type_name', models.CharField(max_length=65)),
                ('indicator_type_order', models.IntegerField(default=0)),
                ('report_type', models.CharField(choices=[('Leading', 'Leading'), ('Lagging', 'Lagging')], max_length=7)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_indicator_type',
                'ordering': ['report_type', 'indicator_type_order'],
            },
        ),
        migrations.CreateModel(
            name='MstPartsOfBody',
            fields=[
                ('part_of_body_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_of_body_name', models.CharField(max_length=60)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_parts_of_body',
            },
        ),
        migrations.CreateModel(
            name='MstQhseCategory',
            fields=[
                ('qhse_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('qhse_category_name', models.CharField(max_length=100)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_qhse_category',
            },
        ),
        migrations.CreateModel(
            name='MstRigOperation',
            fields=[
                ('rig_operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('rig_operation_name', models.CharField(max_length=65)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_rig_operation',
            },
        ),
        migrations.CreateModel(
            name='MstIndicatorSubtype',
            fields=[
                ('indicator_subtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_subtype_name', models.CharField(max_length=65)),
                ('indicator_subtype_order', models.IntegerField(default=0)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('indicator_type', models.ForeignKey(db_column='indicator_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='core.mstindicatortype')),
            ],
            options={
                'db_table': 'mst_indicator_subtype',
                'ordering': ['indicator_type__indicator_type_name', 'indicator_subtype_order'],
            },
        ),
    ]
