# Generated by Django 5.2.17 on 2026-08-20 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mstcontactexposuretype_msthazardtype_msthseactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstEmployee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_fname', models.CharField(blank=True, max_length=26, null=True)),
                ('emp_mname', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_sname', models.CharField(max_length=35)),
                ('emp_active', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'mst_employee',
            },
        ),
        migrations.CreateModel(
            name='DocToSignMapping',
            fields=[
                ('doc_to_sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=50)),
                ('sign_path', models.CharField(blank=True, max_length=100, null=True)),
                ('sign_from', models.DateField()),
                ('sign_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstemployee')),
            ],
            options={
                'db_table': 'doc_to_sign_mapping',
            },
        ),
        migrations.CreateModel(
            name='MstInterviewer',
            fields=[
                ('interviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_path', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstdepartment')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstuser')),
            ],
            options={
                'db_table': 'mst_interviewer',
            },
        ),
        migrations.CreateModel(
            name='MstUserFsCatgMapping',
            fields=[
                ('user_fs_catg_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('mapping_from', models.DateField()),
                ('mapping_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstfscategory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='fs_catg_mappings', to='core.mstuser')),
            ],
            options={
                'db_table': 'user_fs_catg_mapping',
            },
        ),
        migrations.CreateModel(
            name='MstUserRigMapping',
            fields=[
                ('user_rig_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('mapping_from', models.DateField()),
                ('mapping_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstrig')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='rig_mappings', to='core.mstuser')),
            ],
            options={
                'db_table': 'user_rig_mapping',
            },
        ),
    ]
