# Generated by Django 5.2.17 on 2026-08-23 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mstemployee_doctosignmapping_mstinterviewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstCurrency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=30)),
                ('currency_abrv', models.CharField(max_length=3)),
                ('decimal_name', models.CharField(max_length=15)),
                ('currency_text', models.CharField(max_length=25)),
                ('currency_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_currency',
            },
        ),
        migrations.CreateModel(
            name='MstDrillingRate',
            fields=[
                ('drilling_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_code', models.CharField(max_length=20)),
                ('rate_description', models.CharField(blank=True, max_length=50, null=True)),
                ('rate_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_drilling_rate',
            },
        ),
        migrations.CreateModel(
            name='MstLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('country_id', models.IntegerField()),
                ('country_state_id', models.IntegerField(blank=True, null=True)),
                ('location_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_location',
            },
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('prj_contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('prj_contract_no', models.CharField(max_length=110)),
                ('prj_short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('prj_start_dt', models.DateField()),
                ('prj_end_dt', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstlocation')),
                ('operator', models.ForeignKey(db_column='operator_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstoperator')),
            ],
            options={
                'db_table': 'project_contract',
            },
        ),
        migrations.CreateModel(
            name='ProjectContractDtl',
            fields=[
                ('prj_contract_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('rig_active_from', models.DateField()),
                ('rig_active_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(db_column='prj_contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.projectcontract')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstrig')),
            ],
            options={
                'db_table': 'project_contract_dtl',
                'ordering': ['rig_active_from'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDrillingRate',
            fields=[
                ('prj_drilling_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(db_column='prj_contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='drilling_rates', to='core.projectcontract')),
                ('currency', models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mstcurrency')),
                ('drilling_rate', models.ForeignKey(db_column='drilling_rate_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstdrillingrate')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstrig')),
            ],
            options={
                'db_table': 'project_drilling_rate',
            },
        ),
    ]
