# Generated by Django 5.2.17 on 2026-08-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mstcurrency_mstdrillingrate_mstlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstDrillingOperation',
            fields=[
                ('drilling_ops_id', models.AutoField(primary_key=True, serialize=False)),
                ('drilling_ops_code_no', models.IntegerField()),
                ('drilling_ops_name', models.CharField(max_length=50)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_drilling_operation',
            },
        ),
        migrations.CreateModel(
            name='MstDrillingSection',
            fields=[
                ('drilling_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('drilling_section_name', models.CharField(max_length=10)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_drilling_section',
            },
        ),
    ]
