# Generated by Django 5.2.17 on 2026-08-23 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mstdrillingoperation_mstdrillingsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstDrillingWorkShift',
            fields=[
                ('drilling_work_shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_shift', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1)),
                ('work_shift_start_time', models.TimeField()),
                ('work_shift_end_time', models.TimeField()),
                ('work_shift_days', models.IntegerField()),
                ('work_shift_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, db_column='prj_contract_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='core.projectcontract')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, to='core.mstrig')),
            ],
            options={
                'db_table': 'mst_drilling_work_shift',
            },
        ),
    ]
