# Generated by Django 5.2.17 on 2026-08-23 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mstdrillingworkshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdrillingrate',
            name='drilling_rate',
            field=models.ForeignKey(db_column='drilling_rate_id', on_delete=django.db.models.deletion.PROTECT, related_name='rate_usages', to='core.mstdrillingrate'),
        ),
    ]
