# Generated by Django 5.2.17 on 2026-08-24 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_wire_up_fk_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstFinancialYear',
            fields=[
                ('financial_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('fin_year_from', models.DateField()),
                ('fin_year_to', models.DateField()),
                ('fin_year_text', models.CharField(max_length=9)),
                ('fin_year_subtext', models.CharField(max_length=5)),
                ('assessment_year', models.CharField(max_length=9)),
                ('nri_days', models.IntegerField()),
                ('fin_year_status', models.CharField(max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_financial_year',
            },
        ),
        migrations.CreateModel(
            name='MstIncidentCause',
            fields=[
                ('incident_cause_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_cause_desc', models.CharField(max_length=65)),
                ('incident_cause_category', models.CharField(max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_incident_cause',
            },
        ),
        migrations.CreateModel(
            name='MstIncidentType',
            fields=[
                ('incident_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=50)),
                ('incident_abrv', models.CharField(max_length=5)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_incident_type',
            },
        ),
        migrations.CreateModel(
            name='MstWorkLocation',
            fields=[
                ('work_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_location', models.CharField(max_length=45)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_work_location',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, max_length=35, null=True)),
                ('rig_incident_no', models.CharField(blank=True, max_length=20, null=True)),
                ('incident_no', models.IntegerField()),
                ('incident_date', models.DateTimeField()),
                ('well_no', models.CharField(blank=True, max_length=20, null=True)),
                ('drilling_superintendent', models.CharField(blank=True, max_length=40, null=True)),
                ('safety_officer', models.CharField(blank=True, max_length=40, null=True)),
                ('incident_party', models.CharField(blank=True, max_length=3, null=True)),
                ('incident_descr', models.CharField(max_length=1000)),
                ('incident_severity_potential', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_severity', models.CharField(max_length=1)),
                ('immediate_cause_descr', models.CharField(blank=True, max_length=500, null=True)),
                ('corrective_action', models.CharField(blank=True, max_length=300, null=True)),
                ('preventive_action', models.CharField(blank=True, max_length=250, null=True)),
                ('npt_hrs_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manhours_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financial_loss_amt', models.IntegerField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('financial_loss_bc_amt', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('third_party', models.CharField(blank=True, max_length=3, null=True)),
                ('incident_reported_dt', models.DateTimeField(blank=True, null=True)),
                ('person_injured', models.CharField(blank=True, max_length=1, null=True)),
                ('emp_name', models.CharField(blank=True, max_length=75, null=True)),
                ('rank_name', models.CharField(blank=True, max_length=35, null=True)),
                ('total_rig_exp_months', models.IntegerField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=50, null=True)),
                ('dms_path_qhse', models.CharField(blank=True, max_length=250, null=True)),
                ('marked_as_deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('deleted_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('contact_expo_type', models.ForeignKey(blank=True, db_column='contact_expo_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstcontactexposuretype')),
                ('contractor', models.ForeignKey(blank=True, db_column='contractor_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstcontractor')),
                ('country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstcountry')),
                ('financial_loss_currency', models.ForeignKey(blank=True, db_column='financial_loss_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstcurrency')),
                ('fs_emp', models.ForeignKey(blank=True, db_column='fs_emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstemployee')),
                ('operator', models.ForeignKey(blank=True, db_column='operator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstoperator')),
                ('part_of_body_1', models.ForeignKey(blank=True, db_column='part_of_body_id_1', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_as_pob1', to='core.mstpartsofbody')),
                ('part_of_body_2', models.ForeignKey(blank=True, db_column='part_of_body_id_2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_as_pob2', to='core.mstpartsofbody')),
                ('part_of_body_3', models.ForeignKey(blank=True, db_column='part_of_body_id_3', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_as_pob3', to='core.mstpartsofbody')),
                ('part_of_body_4', models.ForeignKey(blank=True, db_column='part_of_body_id_4', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_as_pob4', to='core.mstpartsofbody')),
                ('rank', models.ForeignKey(blank=True, db_column='rank_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstrank')),
                ('rig', models.ForeignKey(blank=True, db_column='rig_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstrig')),
                ('rig_operation', models.ForeignKey(blank=True, db_column='rig_operation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstrigoperation')),
                ('rptd_by_rank', models.ForeignKey(blank=True, db_column='rptd_by_rank_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_as_reporter', to='core.mstrank')),
                ('financial_year', models.ForeignKey(db_column='financial_year_id', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstfinancialyear')),
                ('immediate_incident_cause', models.ForeignKey(db_column='immediate_incident_cause_id', on_delete=django.db.models.deletion.PROTECT, related_name='incidents_as_cause', to='core.mstincidentcause')),
                ('immediate_incident_cause_2', models.ForeignKey(blank=True, db_column='immediate_incident_cause_id_2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_as_cause_2', to='core.mstincidentcause')),
                ('incident_type', models.ForeignKey(db_column='incident_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstincidenttype')),
                ('work_location', models.ForeignKey(blank=True, db_column='work_location_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.mstworklocation')),
            ],
            options={
                'db_table': 'incident',
            },
        ),
    ]
