# Generated by Django 5.2.17 on 2026-08-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_incident_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAction',
            fields=[
                ('incident_action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_recommended', models.CharField(max_length=500)),
                ('action_taken', models.CharField(blank=True, max_length=250, null=True)),
                ('action_party', models.CharField(max_length=100)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_dt', models.DateField(blank=True, null=True)),
                ('action_status', models.CharField(max_length=2)),
                ('marked_as_deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('deleted_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.incident')),
            ],
            options={
                'db_table': 'incident_action',
            },
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('incident_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_photo_path', models.CharField(max_length=50)),
                ('incident_photo_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.incident')),
            ],
            options={
                'db_table': 'incident_photo',
            },
        ),
        migrations.CreateModel(
            name='MstIncidentSubcause',
            fields=[
                ('incident_subcause_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_subcause', models.CharField(max_length=75)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('incident_cause', models.ForeignKey(db_column='incident_cause_id', on_delete=django.db.models.deletion.PROTECT, related_name='subcauses', to='core.mstincidentcause')),
            ],
            options={
                'db_table': 'mst_incident_subcause',
            },
        ),
        migrations.CreateModel(
            name='IncidentRootCause',
            fields=[
                ('incident_root_cause_id', models.AutoField(primary_key=True, serialize=False)),
                ('root_subcause_others', models.CharField(blank=True, max_length=100, null=True)),
                ('marked_as_deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('deleted_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='core.incident')),
                ('root_cause', models.ForeignKey(db_column='root_cause_id', on_delete=django.db.models.deletion.PROTECT, related_name='as_root_cause', to='core.mstincidentcause')),
                ('root_subcause', models.ForeignKey(db_column='root_subcause_id', on_delete=django.db.models.deletion.PROTECT, related_name='as_root_subcause', to='core.mstincidentsubcause')),
            ],
            options={
                'db_table': 'incident_root_cause',
            },
        ),
    ]
