# Generated by Django 5.2.17 on 2026-08-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_incident_child_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardCard',
            fields=[
                ('haz_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('haz_id_card_no', models.IntegerField(blank=True, null=True)),
                ('event_dt', models.DateTimeField()),
                ('reported_by_party', models.CharField(max_length=15)),
                ('reported_by_name', models.CharField(blank=True, max_length=30, null=True)),
                ('timeout_for_safety', models.CharField(max_length=1)),
                ('hazard_desc', models.CharField(max_length=200)),
                ('action_taken', models.CharField(blank=True, max_length=200, null=True)),
                ('close_out_dt', models.DateTimeField(blank=True, null=True)),
                ('haz_id_card_status', models.CharField(max_length=1)),
                ('marked_as_deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('deleted_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('client_key_id', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=20, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(db_column='prj_contract_id', on_delete=django.db.models.deletion.PROTECT, related_name='hazard_cards', to='core.projectcontract')),
                ('haz_type', models.ForeignKey(db_column='haz_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='hazard_cards', to='core.msthazardtype')),
                ('reported_by_fs_emp', models.ForeignKey(blank=True, db_column='reported_by_fs_emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hazard_cards_reported', to='core.mstemployee')),
                ('resp_dept', models.ForeignKey(db_column='resp_dept_id', on_delete=django.db.models.deletion.PROTECT, related_name='hazard_cards', to='core.mstdepartment')),
                ('resp_rank', models.ForeignKey(db_column='resp_rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='hazard_cards', to='core.mstrank')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='hazard_cards', to='core.mstrig')),
                ('work_location', models.ForeignKey(db_column='work_location_id', on_delete=django.db.models.deletion.PROTECT, related_name='hazard_cards', to='core.mstworklocation')),
            ],
            options={
                'db_table': 'hazard_card',
            },
        ),
    ]
