# Generated by Django 5.2.17 on 2026-08-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_hazard_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='FsCatgToRigTypeMapping',
            fields=[
                ('fs_catg_to_rig_type_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('mapping_active', models.CharField(default='N', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='rig_type_mappings', to='core.mstfscategory')),
                ('rig_type', models.ForeignKey(db_column='rig_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='fs_category_mappings', to='core.mstrigtype')),
            ],
            options={
                'db_table': 'fs_catg_to_rig_type_mapping',
            },
        ),
    ]
