# Generated by Django 5.2.17 on 2026-08-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fs_catg_to_rig_type_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstGrade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(blank=True, max_length=15)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_grade',
            },
        ),
        migrations.CreateModel(
            name='RankToGradeMapping',
            fields=[
                ('rank_to_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('grade', models.ForeignKey(db_column='grade_id', on_delete=django.db.models.deletion.PROTECT, related_name='rank_mappings', to='core.mstgrade')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='grade_mappings', to='core.mstrank')),
            ],
            options={
                'db_table': 'rank_to_grade_mapping',
            },
        ),
    ]
