# Generated by Django 5.2.17 on 2026-08-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rank_to_grade_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranktogrademapping',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='ranktogrademapping',
            name='rank',
        ),
        migrations.DeleteModel(
            name='MstGrade',
        ),
        migrations.DeleteModel(
            name='RankToGradeMapping',
        ),
    ]
