# Generated by Django 5.2.17 on 2026-08-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_rank_to_grade_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankClassification',
            fields=[
                ('rank_classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_class', models.CharField(choices=[('J', 'Junior'), ('S', 'Senior')], max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('rank', models.OneToOneField(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='classification', to='core.mstrank')),
            ],
            options={
                'db_table': 'rank_classification',
            },
        ),
    ]
