# Generated by Django 5.2.17 on 2026-08-24 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rank_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstEmpNature',
            fields=[
                ('emp_nature_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nature_name', models.CharField(max_length=50)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_emp_nature',
            },
        ),
        migrations.CreateModel(
            name='MstEmpType',
            fields=[
                ('emp_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_type_name', models.CharField(max_length=45)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emp_types', to='core.mstcurrency')),
                ('emp_nature', models.ForeignKey(db_column='emp_nature_id', on_delete=django.db.models.deletion.PROTECT, related_name='emp_types', to='core.mstempnature')),
            ],
            options={
                'db_table': 'mst_emp_type',
            },
        ),
        migrations.CreateModel(
            name='NationalityToEmpTypeMapping',
            fields=[
                ('nat_to_emp_type_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('nationality', models.CharField(choices=[('National', 'National'), ('Expat', 'Expat')], max_length=8)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('emp_type', models.ForeignKey(db_column='emp_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='nationality_mappings', to='core.mstemptype')),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='nat_emp_type_mappings', to='core.mstfscategory')),
            ],
            options={
                'db_table': 'nationality_to_emp_type_mapping',
            },
        ),
    ]
