# Generated by Django 5.2.17 on 2026-08-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_nationality_emp_type_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewChangeRelieverMapping',
            fields=[
                ('cc_reliever_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='reliever_mappings', to='core.mstfscategory')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='reliever_mappings_as_rank', to='core.mstrank')),
                ('reliever_rank', models.ForeignKey(db_column='reliever_rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='reliever_mappings_as_reliever', to='core.mstrank')),
            ],
            options={
                'db_table': 'crew_change_reliever_mapping',
            },
        ),
    ]
