# Generated by Django 5.2.17 on 2026-08-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_crew_change_reliever_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstWorkgroup',
            fields=[
                ('workgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('workgroup_name', models.CharField(max_length=15)),
                ('workgroup_order', models.IntegerField(default=0)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_workgroup',
            },
        ),
        migrations.CreateModel(
            name='WkgrpIndicatorTypeMapping',
            fields=[
                ('wkgrp_ind_type_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('indicator_type', models.ForeignKey(db_column='indicator_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='workgroup_mappings', to='core.mstindicatortype')),
                ('workgroup', models.ForeignKey(db_column='workgroup_id', on_delete=django.db.models.deletion.PROTECT, related_name='indicator_type_mappings', to='core.mstworkgroup')),
            ],
            options={
                'db_table': 'wkgrp_indicator_type_mapping',
            },
        ),
    ]
