# Generated by Django 5.2.17 on 2026-08-25 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_wkgrp_indicator_type_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstOrganisationalGrp',
            fields=[
                ('organisational_grp_id', models.AutoField(primary_key=True, serialize=False)),
                ('organisational_grp_name', models.CharField(blank=True, max_length=50)),
                ('organisational_grp_abrv', models.CharField(blank=True, max_length=10)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_organisational_grp',
            },
        ),
        migrations.CreateModel(
            name='MstBusinessGrp',
            fields=[
                ('business_grp_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_grp_name', models.CharField(max_length=50)),
                ('business_grp_abrv', models.CharField(max_length=15)),
                ('business_grp_order', models.IntegerField(default=0)),
                ('business_grp_from', models.DateField()),
                ('business_grp_to', models.DateField(blank=True, null=True)),
                ('business_grp_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('parent_business_grp', models.ForeignKey(blank=True, db_column='parent_business_grp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.mstbusinessgrp')),
            ],
            options={
                'db_table': 'mst_business_grp',
            },
        ),
        migrations.CreateModel(
            name='MstCompany',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=75)),
                ('company_abrv', models.CharField(max_length=8)),
                ('company_code', models.CharField(blank=True, max_length=4, null=True)),
                ('company_order', models.IntegerField(blank=True, null=True)),
                ('company_from', models.DateField()),
                ('company_to', models.DateField(blank=True, null=True)),
                ('company_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('business_grp', models.ForeignKey(db_column='business_grp_id', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.mstbusinessgrp')),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.mstcountry')),
                ('currency', models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.mstcurrency')),
                ('parent_company', models.ForeignKey(blank=True, db_column='parent_company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='core.mstcompany')),
                ('organisational_grp', models.ForeignKey(db_column='organisational_grp_id', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.mstorganisationalgrp')),
            ],
            options={
                'db_table': 'mst_company',
            },
        ),
        migrations.CreateModel(
            name='CostCentreToCompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_from', models.DateField()),
                ('mapping_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('cost_centre', models.ForeignKey(db_column='cost_centre_id', on_delete=django.db.models.deletion.PROTECT, related_name='company_mappings', to='core.mstcostcentre')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='cost_centre_mappings', to='core.mstcompany')),
            ],
            options={
                'db_table': 'cost_centre_to_company_mapping',
            },
        ),
    ]
