# Generated by Django 5.2.17 on 2026-08-25 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_cost_centre_to_company_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigSiteMapping',
            fields=[
                ('rig_site_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('camp_office_addr', models.CharField(max_length=150)),
                ('contact_tel_no_1', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_tel_no_2', models.CharField(blank=True, max_length=10, null=True)),
                ('site_from', models.DateField()),
                ('site_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='rig_site_mappings', to='core.mstcompany')),
                ('contact_fs_emp_1', models.ForeignKey(blank=True, db_column='contact_fs_emp_id_1', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rig_site_contacts_1', to='core.mstemployee')),
                ('contact_fs_emp_2', models.ForeignKey(blank=True, db_column='contact_fs_emp_id_2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rig_site_contacts_2', to='core.mstemployee')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, related_name='rig_site_mappings', to='core.mstlocation')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='site_mappings', to='core.mstrig')),
            ],
            options={
                'db_table': 'rig_site_mapping',
            },
        ),
    ]
