# Generated by Django 5.2.17 on 2026-08-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rig_crew_exception'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewScheduleException',
            fields=[
                ('cs_exception_id', models.AutoField(primary_key=True, serialize=False)),
                ('exception_from', models.DateField()),
                ('exception_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('emp_type', models.ForeignKey(blank=True, db_column='emp_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_exceptions', to='core.mstemptype')),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='schedule_exceptions', to='core.mstfscategory')),
                ('fs_emp', models.ForeignKey(blank=True, db_column='fs_emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_exceptions', to='core.mstemployee')),
                ('rank', models.ForeignKey(blank=True, db_column='rank_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_exceptions', to='core.mstrank')),
            ],
            options={
                'db_table': 'crew_schedule_exception',
            },
        ),
    ]
