# Generated by Django 5.2.17 on 2026-08-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_crew_schedule_exception'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstItAccessory',
            fields=[
                ('it_accessory_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_accessory_name', models.CharField(max_length=30)),
                ('it_accessory_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_it_accessory',
            },
        ),
        migrations.CreateModel(
            name='MstItAssetMfg',
            fields=[
                ('it_asset_mfg_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_asset_mfg_name', models.CharField(max_length=30)),
                ('it_asset_mfg_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_it_asset_mfg',
            },
        ),
        migrations.CreateModel(
            name='MstItAssetSubtype',
            fields=[
                ('it_asset_subtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_asset_subtype_name', models.CharField(max_length=30)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_it_asset_subtype',
            },
        ),
        migrations.CreateModel(
            name='MstItAssetType',
            fields=[
                ('it_asset_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_asset_type_name', models.CharField(max_length=20)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_it_asset_type',
            },
        ),
        migrations.CreateModel(
            name='MstVendorType',
            fields=[
                ('vendor_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_type_name', models.CharField(max_length=30)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_vendor_type',
            },
        ),
        migrations.CreateModel(
            name='MstVesselType',
            fields=[
                ('vessel_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vessel_type_name', models.CharField(max_length=30)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_vessel_type',
            },
        ),
        migrations.CreateModel(
            name='MstCompanyLocation',
            fields=[
                ('company_loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_loc_name', models.CharField(max_length=75)),
                ('company_loc_abrv', models.CharField(blank=True, max_length=8, null=True)),
                ('company_loc_address', models.CharField(blank=True, max_length=150, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=14, null=True)),
                ('longitude', models.CharField(blank=True, max_length=14, null=True)),
                ('company_loc_type', models.CharField(max_length=1)),
                ('company_loc_ownership', models.CharField(blank=True, max_length=1, null=True)),
                ('company_loc_order', models.IntegerField(default=0)),
                ('company_loc_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, related_name='company_locations', to='core.mstcountry')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, related_name='company_locations', to='core.mstlocation')),
            ],
            options={
                'db_table': 'mst_company_location',
            },
        ),
        migrations.CreateModel(
            name='MstItAssetModel',
            fields=[
                ('it_asset_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_asset_model_name', models.CharField(max_length=50)),
                ('it_asset_model_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('it_asset_mfg', models.ForeignKey(db_column='it_asset_mfg_id', on_delete=django.db.models.deletion.PROTECT, related_name='models', to='core.mstitassetmfg')),
                ('it_asset_subtype', models.ForeignKey(db_column='it_asset_subtype_id', on_delete=django.db.models.deletion.PROTECT, related_name='models', to='core.mstitassetsubtype')),
            ],
            options={
                'db_table': 'mst_it_asset_model',
            },
        ),
        migrations.AddField(
            model_name='mstitassetsubtype',
            name='it_asset_type',
            field=models.ForeignKey(db_column='it_asset_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='core.mstitassettype'),
        ),
        migrations.CreateModel(
            name='MstVesselSubtype',
            fields=[
                ('vessel_subtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('vessel_subtype_name', models.CharField(max_length=30)),
                ('vessel_subtype_order', models.IntegerField(default=0)),
                ('vessel_subtype_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('vessel_type', models.ForeignKey(db_column='vessel_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='core.mstvesseltype')),
            ],
            options={
                'db_table': 'mst_vessel_subtype',
            },
        ),
        migrations.CreateModel(
            name='MstVessel',
            fields=[
                ('vessel_id', models.AutoField(primary_key=True, serialize=False)),
                ('vessel_name', models.CharField(max_length=40)),
                ('own_ship_co_id', models.IntegerField()),
                ('mgr_ship_co_id', models.IntegerField()),
                ('imo_no', models.IntegerField()),
                ('vessel_from', models.DateField()),
                ('vessel_to', models.DateField(blank=True, null=True)),
                ('vessel_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('flag_country', models.ForeignKey(db_column='flag_country_id', on_delete=django.db.models.deletion.PROTECT, related_name='flagged_vessels', to='core.mstcountry')),
                ('vessel_subtype', models.ForeignKey(db_column='vessel_subtype_id', on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='core.mstvesselsubtype')),
                ('vessel_type', models.ForeignKey(db_column='vessel_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='core.mstvesseltype')),
            ],
            options={
                'db_table': 'mst_vessel',
            },
        ),
        migrations.CreateModel(
            name='MstxVendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_sap_code', models.IntegerField(blank=True, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_tel_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('vendor_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='core.mstcountry')),
                ('currency', models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='core.mstcurrency')),
                ('vendor_type', models.ForeignKey(db_column='vendor_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='core.mstvendortype')),
            ],
            options={
                'db_table': 'mstx_vendor',
            },
        ),
    ]
