# Generated by Django 5.2.17 on 2026-08-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_it_module_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstvendortype',
            name='vendor_type_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mstvesselsubtype',
            name='vessel_subtype_name',
            field=models.CharField(max_length=40),
        ),
    ]
