# Generated by Django 5.2.17 on 2026-08-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_it_module_lookup_field_lengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstvesselsubtype',
            name='vessel_type',
        ),
        migrations.DeleteModel(
            name='MstVessel',
        ),
        migrations.DeleteModel(
            name='MstVesselSubtype',
        ),
        migrations.DeleteModel(
            name='MstVesselType',
        ),
    ]
