# Generated by Django 5.2.17 on 2026-08-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_vessel_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstItApplicationType',
            fields=[
                ('it_appl_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_appl_type_name', models.CharField(max_length=20)),
                ('max_resources', models.IntegerField()),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_it_application_type',
            },
        ),
        migrations.CreateModel(
            name='MstItApplicationSubtype',
            fields=[
                ('it_appl_subtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_appl_subtype_name', models.CharField(max_length=40)),
                ('max_resources', models.IntegerField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('it_appl_type', models.ForeignKey(db_column='it_appl_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='core.mstitapplicationtype')),
            ],
            options={
                'db_table': 'mst_it_application_subtype',
            },
        ),
    ]
