# Generated by Django 5.2.17 on 2026-08-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_it_application_type_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItAccessoryHolder',
            fields=[
                ('it_accessory_holder_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_accessory_holder_name', models.CharField(blank=True, max_length=40, null=True)),
                ('it_accessory_model', models.CharField(blank=True, max_length=20, null=True)),
                ('it_accessory_sr_no', models.CharField(blank=True, max_length=40, null=True)),
                ('it_accessory_product_no', models.CharField(blank=True, max_length=40, null=True)),
                ('it_accessory_holder_from', models.DateField()),
                ('it_accessory_holder_remark', models.CharField(blank=True, max_length=50, null=True)),
                ('it_accessory_holder_to', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('emp', models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_accessory_holdings', to='core.mstemployee')),
                ('it_accessory', models.ForeignKey(db_column='it_accessory_id', on_delete=django.db.models.deletion.PROTECT, related_name='holders', to='core.mstitaccessory')),
                ('it_asset_mfg', models.ForeignKey(blank=True, db_column='it_asset_mfg_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_holdings', to='core.mstitassetmfg')),
            ],
            options={
                'db_table': 'it_accessory_holder',
            },
        ),
        migrations.CreateModel(
            name='MstItAsset',
            fields=[
                ('it_asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_asset_mac_addr', models.CharField(blank=True, max_length=17, null=True)),
                ('it_asset_sr_no', models.CharField(max_length=40)),
                ('it_asset_tag', models.CharField(blank=True, max_length=40, null=True)),
                ('it_asset_sap_code', models.CharField(blank=True, max_length=10, null=True)),
                ('it_asset_ram', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('it_asset_hdd', models.IntegerField(blank=True, null=True)),
                ('it_asset_particulars', models.CharField(blank=True, max_length=75, null=True)),
                ('it_asset_product_no', models.CharField(blank=True, max_length=40, null=True)),
                ('po_no', models.CharField(blank=True, max_length=20, null=True)),
                ('po_dt', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=20, null=True)),
                ('it_asset_pur_dt', models.DateField(blank=True, null=True)),
                ('it_asset_warranty_upto', models.DateField(blank=True, null=True)),
                ('it_asset_amc_dt', models.DateField(blank=True, null=True)),
                ('it_asset_holder_type', models.CharField(max_length=1)),
                ('remarks', models.CharField(blank=True, max_length=75, null=True)),
                ('it_asset_allocated', models.CharField(max_length=1)),
                ('it_asset_active', models.CharField(default='Y', max_length=1)),
                ('it_asset_to_dt', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('company_loc', models.ForeignKey(blank=True, db_column='company_loc_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_assets', to='core.mstcompanylocation')),
                ('cur_company', models.ForeignKey(db_column='cur_company_id', on_delete=django.db.models.deletion.PROTECT, related_name='held_it_assets', to='core.mstcompany')),
                ('department', models.ForeignKey(blank=True, db_column='dept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_assets', to='core.mstdepartment')),
                ('emp', models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_assets', to='core.mstemployee')),
                ('it_asset_mfg', models.ForeignKey(blank=True, db_column='it_asset_mfg_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.mstitassetmfg')),
                ('it_asset_model', models.ForeignKey(blank=True, db_column='it_asset_model_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.mstitassetmodel')),
                ('it_asset_subtype', models.ForeignKey(db_column='it_asset_subtype_id', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.mstitassetsubtype')),
                ('it_asset_type', models.ForeignKey(db_column='it_asset_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.mstitassettype')),
                ('own_company', models.ForeignKey(db_column='own_company_id', on_delete=django.db.models.deletion.PROTECT, related_name='owned_it_assets', to='core.mstcompany')),
                ('vendor', models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_assets', to='core.mstxvendor')),
            ],
            options={
                'db_table': 'mst_it_asset',
            },
        ),
        migrations.CreateModel(
            name='ItAssetHolder',
            fields=[
                ('it_asset_holder_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_asset_holder_from', models.DateField()),
                ('vessel_id', models.IntegerField(blank=True, null=True)),
                ('holder_name', models.CharField(blank=True, max_length=40, null=True)),
                ('holder_remark', models.CharField(blank=True, max_length=150, null=True)),
                ('it_asset_holder_to', models.DateField(blank=True, null=True)),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('company_loc', models.ForeignKey(blank=True, db_column='company_loc_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_asset_holdings', to='core.mstcompanylocation')),
                ('department', models.ForeignKey(blank=True, db_column='dept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_asset_holdings', to='core.mstdepartment')),
                ('emp', models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_asset_holdings', to='core.mstemployee')),
                ('holder_company', models.ForeignKey(db_column='holder_company_id', on_delete=django.db.models.deletion.PROTECT, related_name='it_asset_holdings', to='core.mstcompany')),
                ('it_asset', models.ForeignKey(db_column='it_asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='core.mstitasset')),
            ],
            options={
                'db_table': 'it_asset_holder',
            },
        ),
    ]
