# Generated by Django 5.2.17 on 2026-08-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_it_asset_holders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itassetholder',
            name='vessel_id',
        ),
    ]
