# Generated by Django 5.2.17 on 2026-08-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_it_asset_holder_vessel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itassetholder',
            name='vessel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
