# Generated by Django 5.2.17 on 2026-08-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_restore_it_asset_holder_vessel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionPreset',
            fields=[
                ('preset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('menus_json', models.TextField()),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('cr_dt', models.DateTimeField(auto_now_add=True)),
                ('mod_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_permission_preset',
                'ordering': ['name'],
            },
        ),
    ]
