# Generated by Django 5.2.17 on 2026-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_permission_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstitasset',
            name='it_asset_scrap_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
