# Generated by Django 5.2.17 on 2026-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_mstitasset_it_asset_scrap_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itassetholder',
            name='it_asset_holder_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
