# Generated by Django 5.2.17 on 2026-08-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_itassetholder_it_asset_holder_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstitasset',
            name='it_asset_lost_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
