# Generated by Django 5.2.17 on 2026-08-31 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_mstitasset_it_asset_lost_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='itassetholder',
            name='holder_user',
            field=models.ForeignKey(blank=True, db_column='holder_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_asset_holdings', to='core.mstuser'),
        ),
    ]
