# Generated by Django 5.2.17 on 2026-09-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_itassetholder_holder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstcompany',
            name='cost_center',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='mstcompany',
            name='payroll_area',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='mstcompany',
            name='personnel_area',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='mstcompany',
            name='sap_company',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
