# Generated by Django 5.2.17 on 2026-09-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_mstcompany_cost_center_mstcompany_payroll_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstcompanylocation',
            name='company_loc_voip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
