# Generated by Django 5.2.17 on 2026-09-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_mstcompanylocation_company_loc_voip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstCompanyLocOwnership',
            fields=[
                ('company_loc_ownership_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_loc_ownership_code', models.CharField(max_length=20, unique=True)),
                ('company_loc_ownership_name', models.CharField(max_length=50)),
                ('company_loc_ownership_order', models.IntegerField(default=0)),
                ('company_loc_ownership_active', models.CharField(default='Y', max_length=1)),
                ('cr_dt', models.DateTimeField(auto_now_add=True)),
                ('mod_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_company_loc_ownership',
                'ordering': ['company_loc_ownership_order'],
            },
        ),
        migrations.CreateModel(
            name='MstCompanyLocType',
            fields=[
                ('company_loc_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_loc_type_code', models.CharField(max_length=20, unique=True)),
                ('company_loc_type_name', models.CharField(max_length=50)),
                ('company_loc_type_order', models.IntegerField(default=0)),
                ('company_loc_type_active', models.CharField(default='Y', max_length=1)),
                ('cr_dt', models.DateTimeField(auto_now_add=True)),
                ('mod_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_company_loc_type',
                'ordering': ['company_loc_type_order'],
            },
        ),
        migrations.AlterField(
            model_name='mstcompanylocation',
            name='company_loc_ownership',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mstcompanylocation',
            name='company_loc_type',
            field=models.CharField(max_length=20),
        ),
    ]
