# Generated by Django 5.2.17 on 2026-09-01 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_mstcompanylocownership_mstcompanyloctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyToLocationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_addr_type', models.CharField(blank=True, max_length=10, null=True)),
                ('company_loc_mapp_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='location_mappings', to='core.mstcompany')),
                ('company_loc', models.ForeignKey(db_column='company_loc_id', on_delete=django.db.models.deletion.PROTECT, related_name='company_mappings', to='core.mstcompanylocation')),
            ],
            options={
                'db_table': 'company_to_location_mapping',
            },
        ),
    ]
