# Generated by Django 5.2.17 on 2026-09-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_companytolocationmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstfinancialyear',
            name='fin_year_status',
        ),
        migrations.RemoveField(
            model_name='mstfinancialyear',
            name='nri_days',
        ),
    ]
