# Generated by Django 5.2.17 on 2026-09-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_financial_year_nri_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstBussCertIssueAuthority',
            fields=[
                ('buss_cert_issue_auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('buss_cert_issue_authority', models.CharField(max_length=75)),
                ('buss_cert_issue_abrv', models.CharField(max_length=7)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_buss_cert_issue_authority',
            },
        ),
    ]
