# Generated by Django 5.2.17 on 2026-09-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_mst_buss_cert_issue_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstBussCertType',
            fields=[
                ('buss_cert_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('buss_cert_type', models.CharField(max_length=15)),
                ('buss_cert_type_abrv', models.CharField(max_length=5)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_buss_cert_type',
            },
        ),
    ]
