# Generated by Django 5.2.17 on 2026-09-03 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_mst_buss_cert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstBussCert',
            fields=[
                ('buss_cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('buss_cert_name', models.CharField(max_length=90)),
                ('buss_cert_validity', models.CharField(max_length=15)),
                ('business_system_id_2', models.IntegerField(blank=True, null=True)),
                ('business_system_id_5', models.IntegerField(blank=True, null=True)),
                ('business_system_id_6', models.IntegerField(blank=True, null=True)),
                ('business_system_id_7', models.IntegerField(blank=True, null=True)),
                ('business_system_id_8', models.IntegerField(blank=True, null=True)),
                ('business_system_id_9', models.IntegerField(blank=True, null=True)),
                ('business_system_id_11', models.IntegerField(blank=True, null=True)),
                ('buss_cert_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('buss_cert_type', models.ForeignKey(db_column='buss_cert_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='core.mstbusscerttype')),
            ],
            options={
                'db_table': 'mst_buss_cert',
            },
        ),
    ]
