# Generated by Django 5.2.17 on 2026-09-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_mst_buss_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstvesseldept',
            name='business_system_id_11',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mstvesseldept',
            name='business_system_id_2',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mstvesseldept',
            name='business_system_id_5',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mstvesseldept',
            name='business_system_id_6',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
