# Generated by Django 5.2.17 on 2026-09-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_vessel_dept_business_system_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstCertType',
            fields=[
                ('cert_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_type', models.CharField(max_length=30)),
                ('cert_type_abrv', models.CharField(max_length=10)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_cert_type',
            },
        ),
        migrations.CreateModel(
            name='MstQualification',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification_name', models.CharField(max_length=60)),
                ('qualification_abrv', models.CharField(max_length=15)),
                ('qualification_type', models.CharField(choices=[('Academic', 'Academic'), ('Professional', 'Professional')], max_length=15)),
                ('business_system_id_2', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_6', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_qualification',
            },
        ),
        migrations.CreateModel(
            name='MstCert',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_name', models.CharField(max_length=90)),
                ('cert_abrv', models.CharField(max_length=15)),
                ('business_system_id_2', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_6', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('vessel_dept', models.ForeignKey(blank=True, db_column='vessel_dept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certs', to='core.mstvesseldept')),
                ('cert_type', models.ForeignKey(db_column='cert_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='certs', to='core.mstcerttype')),
            ],
            options={
                'db_table': 'mst_cert',
            },
        ),
    ]
