# Generated by Django 5.2.17 on 2026-09-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_cert_classification_masters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstcerttype',
            name='cert_type',
        ),
        migrations.AddField(
            model_name='mstcert',
            name='cert_training_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mstcerttype',
            name='cert_type_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mstcert',
            name='cert_abrv',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='mstcert',
            name='cert_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='mstcerttype',
            name='cert_type_abrv',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mstqualification',
            name='qualification_abrv',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mstqualification',
            name='qualification_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mstqualification',
            name='qualification_type',
            field=models.CharField(choices=[('A', 'Academic'), ('P', 'Professional')], max_length=1),
        ),
    ]
