# Generated by Django 5.2.17 on 2026-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_cert_classification_field_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstemptype',
            name='business_system_id_11',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mstemptype',
            name='business_system_id_16',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mstemptype',
            name='business_system_id_2',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mstemptype',
            name='business_system_id_5',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mstemptype',
            name='business_system_id_6',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
