# Generated by Django 5.2.17 on 2026-09-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_emp_type_business_system_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstServSubtype',
            fields=[
                ('serv_subtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('serv_subtype_name', models.CharField(max_length=35)),
                ('serv_subtype_abrv', models.CharField(max_length=5)),
                ('business_system_id_2', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_6', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_serv_subtype',
            },
        ),
        migrations.CreateModel(
            name='MstServType',
            fields=[
                ('serv_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('serv_type_name', models.CharField(max_length=12)),
                ('serv_type_abrv', models.CharField(max_length=5)),
                ('business_system_id_2', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_6', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_serv_type',
            },
        ),
        migrations.CreateModel(
            name='MstFsCatgToSstype',
            fields=[
                ('catg_sstype_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_system_id_2', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_5', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_6', models.CharField(blank=True, max_length=1, null=True)),
                ('business_system_id_11', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('emp_type', models.ForeignKey(db_column='emp_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='serv_subtype_mappings', to='core.mstemptype')),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='serv_subtype_mappings', to='core.mstfscategory')),
                ('serv_subtype', models.ForeignKey(db_column='serv_subtype_id', on_delete=django.db.models.deletion.PROTECT, related_name='fs_catg_mappings', to='core.mstservsubtype')),
                ('serv_type', models.ForeignKey(db_column='serv_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='fs_catg_mappings', to='core.mstservtype')),
            ],
            options={
                'db_table': 'mst_fs_catg_to_sstype',
            },
        ),
    ]
