# Generated by Django 5.2.17 on 2026-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_service_particulars_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstRelationDtl',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation', models.CharField(max_length=30)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_relation_dtl',
            },
        ),
    ]
