# Generated by Django 5.2.17 on 2026-09-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_relation_dtl_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstLeavingReason',
            fields=[
                ('leaving_reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('leaving_reason', models.CharField(max_length=40)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_leaving_reason',
            },
        ),
        migrations.CreateModel(
            name='MstLeavingReasonDtl',
            fields=[
                ('leaving_reason_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('leaving_reason_dtl', models.CharField(max_length=40)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('leaving_reason', models.ForeignKey(db_column='leaving_reason_id', on_delete=django.db.models.deletion.PROTECT, related_name='details', to='core.mstleavingreason')),
            ],
            options={
                'db_table': 'mst_leaving_reason_dtl',
            },
        ),
    ]
