# Generated by Django 5.2.17 on 2026-09-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_leaving_reason_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAlertDtl',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('S', 'Scheduled'), ('E', 'Event'), ('U', 'User-based')], max_length=1)),
                ('alert_category', models.CharField(choices=[('A', 'Alert'), ('R', 'Report'), ('M', 'MIS'), ('S', 'Message')], max_length=1)),
                ('alert_name', models.CharField(max_length=60)),
                ('alert_window', models.IntegerField()),
                ('alert_freq', models.IntegerField()),
                ('mail_subject', models.CharField(max_length=60)),
                ('particulars', models.CharField(max_length=125)),
                ('next_mail_dt', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.IntegerField()),
                ('additional_alert', models.CharField(blank=True, max_length=1, null=True)),
                ('alert_display_name', models.CharField(blank=True, max_length=125, null=True)),
                ('alert_active', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mail_alert_dtl',
            },
        ),
        migrations.CreateModel(
            name='MailAlertToUser',
            fields=[
                ('mail_alert_to_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_addr', models.CharField(max_length=45)),
                ('read_receipt', models.CharField(blank=True, max_length=1, null=True)),
                ('mail_alert_from', models.DateField()),
                ('mail_alert_to', models.DateField(blank=True, null=True)),
                ('addressee_type', models.CharField(choices=[('T', 'To'), ('C', 'Cc'), ('B', 'Bcc')], max_length=1)),
                ('mail_alert_order', models.IntegerField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(db_column='alert_id', on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='core.mailalertdtl')),
                ('emp', models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mail_alerts', to='core.mstemployee')),
            ],
            options={
                'db_table': 'mail_alert_to_user',
            },
        ),
        migrations.CreateModel(
            name='MstBusinessSystem',
            fields=[
                ('business_system_id', models.AutoField(primary_key=True, serialize=False)),
                ('buss_system_dtl', models.CharField(max_length=30)),
                ('buss_system_abrv', models.CharField(max_length=6)),
                ('buss_system_schema_name', models.CharField(max_length=6)),
                ('mail_from_address', models.CharField(blank=True, max_length=30, null=True)),
                ('mail_user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mail_user_password', models.CharField(blank=True, max_length=15, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('owner_emp', models.ForeignKey(blank=True, db_column='owner_emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_business_systems', to='core.mstemployee')),
            ],
            options={
                'db_table': 'mst_business_system',
            },
        ),
    ]
