# Generated by Django 5.2.17 on 2026-09-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_mail_alert_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingHdr',
            fields=[
                ('drilling_hdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=14)),
                ('longitude', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=25)),
                ('total_water_depth', models.IntegerField(blank=True, null=True)),
                ('total_depth', models.IntegerField(blank=True, null=True)),
                ('first_anchor_down_dt', models.DateTimeField()),
                ('distance_covered_kms_knots', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tot_consumption_diesel', models.IntegerField(default=0)),
                ('tot_consumption_water', models.IntegerField(default=0)),
                ('tot_received_diesel', models.IntegerField(default=0)),
                ('tot_received_water', models.IntegerField(default=0)),
                ('tot_generated_water', models.IntegerField(default=0)),
                ('tot_operating_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tot_standby_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tot_repair_service_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tot_repair_rate_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tot_zero_rate_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_days', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('drilling_completion_dt', models.DateTimeField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, db_column='prj_contract_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drilling_hdrs', to='core.projectcontract')),
                ('drilling_rate', models.ForeignKey(blank=True, db_column='drilling_rate_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drilling_hdrs', to='core.mstdrillingrate')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='drilling_hdrs', to='core.mstrig')),
            ],
            options={
                'db_table': 'drilling_hdr',
            },
        ),
    ]
