# Generated by Django 5.2.17 on 2026-09-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_drilling_hdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstApprovalCode',
            fields=[
                ('approval_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_code', models.CharField(max_length=20)),
                ('approval_desc', models.CharField(max_length=150)),
                ('approval_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_approval_code',
                'ordering': ['approval_code'],
            },
        ),
        migrations.CreateModel(
            name='ApproverMapping',
            fields=[
                ('approver_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('approver_level', models.IntegerField()),
                ('approver_active', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('approver_user', models.ForeignKey(db_column='approver_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='approver_mappings', to='core.mstuser')),
                ('approval_code', models.ForeignKey(db_column='approval_code_id', on_delete=django.db.models.deletion.PROTECT, related_name='approver_mappings', to='core.mstapprovalcode')),
            ],
            options={
                'db_table': 'approver_mapping',
            },
        ),
        migrations.CreateModel(
            name='ApproverMappingDtl',
            fields=[
                ('approver_mapping_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('receive_mail', models.CharField(blank=True, max_length=1, null=True)),
                ('approve_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('open_for_revision_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('create_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('approver_mapping', models.ForeignKey(db_column='approver_mapping_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.approvermapping')),
                ('dept', models.ForeignKey(blank=True, db_column='dept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver_mapping_dtls', to='core.mstdepartment')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='approver_mapping_dtls', to='core.mstrig')),
            ],
            options={
                'db_table': 'approver_mapping_dtl',
            },
        ),
    ]
