# Generated by Django 5.2.17 on 2026-09-15 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_mstapprovalcode_approvermapping_approvermappingdtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('email_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('recipients', models.TextField()),
                ('trigger', models.CharField(blank=True, max_length=200)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('sent_by_user_id', models.IntegerField(blank=True, null=True)),
                ('sent_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_email_log',
                'ordering': ['-sent_dt'],
            },
        ),
        migrations.CreateModel(
            name='DrillingDtl',
            fields=[
                ('drilling_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('drilling_dtl_dt', models.DateField()),
                ('pob_operator', models.IntegerField()),
                ('pob_essar', models.IntegerField()),
                ('pob_essar_serv', models.IntegerField(blank=True, null=True)),
                ('pob_others', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.IntegerField()),
                ('current_k', models.DecimalField(decimal_places=1, max_digits=2)),
                ('at_press_mbar', models.IntegerField()),
                ('vdl', models.IntegerField()),
                ('avdl', models.IntegerField()),
                ('tot_vdl', models.IntegerField()),
                ('kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('kg_margin', models.DecimalField(decimal_places=2, max_digits=3)),
                ('draft', models.DecimalField(decimal_places=2, max_digits=4)),
                ('consumption_diesel', models.IntegerField()),
                ('consumption_water', models.IntegerField()),
                ('received_diesel', models.IntegerField(blank=True, null=True)),
                ('received_water', models.IntegerField(blank=True, null=True)),
                ('generated_water', models.IntegerField(blank=True, null=True)),
                ('operating_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('standby_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('repair_service_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('repair_rate_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('zero_rate_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rig_move_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('drilling_meterage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('downtime_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('cr_status', models.CharField(blank=True, choices=[('F', 'Finalized'), ('N', 'Reopened for revision')], max_length=1, null=True)),
                ('l1_approval_status', models.CharField(blank=True, choices=[('N', 'Pending'), ('A', 'Approved'), ('R', 'Revise')], max_length=1, null=True)),
                ('l1_approval_dt', models.DateField(blank=True, null=True)),
                ('l1_user_id', models.IntegerField(blank=True, null=True)),
                ('opened_for_revision_by', models.IntegerField(blank=True, null=True)),
                ('opened_for_revision_dt', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('drilling_hdr', models.ForeignKey(blank=True, db_column='drilling_hdr_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drilling_dtls', to='core.drillinghdr')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='drilling_dtls', to='core.mstrig')),
            ],
            options={
                'db_table': 'drilling_dtl',
            },
        ),
        migrations.CreateModel(
            name='DrillingDtlOps',
            fields=[
                ('drilling_dtl_ops_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('work_shift', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('depth_from', models.DecimalField(decimal_places=2, max_digits=6)),
                ('depth_to', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rop_trip_mh', models.IntegerField()),
                ('operation_desc', models.CharField(max_length=200)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('drilling_dtl', models.ForeignKey(db_column='drilling_dtl_id', on_delete=django.db.models.deletion.CASCADE, related_name='ops', to='core.drillingdtl')),
                ('drilling_ops', models.ForeignKey(db_column='drilling_ops_id', on_delete=django.db.models.deletion.PROTECT, related_name='dtl_ops', to='core.mstdrillingoperation')),
                ('drilling_section', models.ForeignKey(db_column='drilling_section_id', on_delete=django.db.models.deletion.PROTECT, related_name='dtl_ops', to='core.mstdrillingsection')),
                ('prj_drilling_rate', models.ForeignKey(db_column='prj_drilling_rate_id', on_delete=django.db.models.deletion.PROTECT, related_name='dtl_ops', to='core.projectdrillingrate')),
            ],
            options={
                'db_table': 'drilling_dtl_ops',
            },
        ),
    ]
