# Generated by Django 5.2.17 on 2026-09-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_emaillog_drillingdtl_drillingdtlops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillingdtl',
            name='l1_approval_status',
            field=models.CharField(blank=True, choices=[('N', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1, null=True),
        ),
    ]
