# Generated by Django 5.2.17 on 2026-09-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_drillingdtl_l1_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillingdtl',
            name='revision_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
