# Generated by Django 5.2.17 on 2026-09-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_drillingdtl_revision_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailCredential',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_user_mail_credential',
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='used_fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MailRecipientMapping',
            fields=[
                ('mail_recipient_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('FINALIZE', 'Finalize'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REVISE_PREVIOUS', 'Revise Previous Level')], max_length=20)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('approval_code', models.ForeignKey(db_column='approval_code_id', on_delete=django.db.models.deletion.PROTECT, related_name='mail_recipient_mappings', to='core.mstapprovalcode')),
                ('mail_alert_to_user', models.ForeignKey(db_column='mail_alert_to_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='recipient_mappings', to='core.mailalerttouser')),
            ],
            options={
                'db_table': 'mail_recipient_mapping',
            },
        ),
    ]
