# Generated by Django 5.2.17 on 2026-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_usermailcredential_emaillog_used_fallback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='trigger_code',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
