# Generated by Django 5.2.17 on 2026-09-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_emaillog_trigger_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigCert',
            fields=[
                ('rig_cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(max_length=30)),
                ('cert_date', models.DateField()),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=75, null=True)),
                ('certificate_path', models.CharField(blank=True, max_length=150, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('buss_cert', models.ForeignKey(db_column='buss_cert_id', on_delete=django.db.models.deletion.PROTECT, related_name='rig_certs', to='core.mstbusscert')),
                ('buss_cert_issue_authority', models.ForeignKey(db_column='buss_cert_issue_auth_id', on_delete=django.db.models.deletion.PROTECT, related_name='rig_certs', to='core.mstbusscertissueauthority')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='rig_certs', to='core.mstrig')),
            ],
            options={
                'db_table': 'rig_cert',
            },
        ),
        migrations.CreateModel(
            name='RigCertSchedule',
            fields=[
                ('rig_cert_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_dt', models.DateField()),
                ('schedule_type', models.CharField(choices=[('A', 'Annual Survey'), ('I', 'Intermediate Survey')], max_length=1)),
                ('remark', models.CharField(blank=True, max_length=75, null=True)),
                ('completion_dt', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('rig_cert', models.ForeignKey(db_column='rig_cert_id', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='core.rigcert')),
            ],
            options={
                'db_table': 'rig_cert_schedule',
            },
        ),
    ]
