# Generated by Django 5.2.17 on 2026-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_rigcert_rigcertschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=80)),
                ('activity_type', models.CharField(choices=[('I', 'Inspection'), ('A', 'Activity')], max_length=1)),
                ('activity_nature', models.CharField(choices=[('M', 'Mandatory'), ('N', 'Non Mandatory')], max_length=1)),
                ('activity_location', models.CharField(choices=[('V', 'Vessel'), ('O', 'Office'), ('P', 'Port'), ('R', 'Rig')], max_length=1)),
                ('intimate_vessel', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('activity_validity_days', models.SmallIntegerField()),
                ('activity_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_activity',
            },
        ),
    ]
