# Generated by Django 5.2.17 on 2026-09-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_mstactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMonitor',
            fields=[
                ('activity_monitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_dt', models.DateField()),
                ('original_scheduled_dt', models.DateField(blank=True, null=True)),
                ('planning_remark', models.CharField(blank=True, max_length=50, null=True)),
                ('completion_dt', models.DateField(blank=True, null=True)),
                ('completion_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.PROTECT, related_name='monitors', to='core.mstactivity')),
                ('rig', models.ForeignKey(blank=True, db_column='rig_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_monitors', to='core.mstrig')),
            ],
            options={
                'db_table': 'activity_monitor',
            },
        ),
    ]
