# Generated by Django 5.2.17 on 2026-09-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_activitymonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNameChange',
            fields=[
                ('company_name_change_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=75)),
                ('company_short_name', models.CharField(blank=True, max_length=75, null=True)),
                ('image_path_header', models.CharField(blank=True, max_length=75, null=True)),
                ('image_path_footer', models.CharField(blank=True, max_length=75, null=True)),
                ('image_path_stamp', models.CharField(blank=True, max_length=75, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='name_changes', to='core.mstcompany')),
            ],
            options={
                'db_table': 'company_name_change',
            },
        ),
    ]
