# Generated by Django 5.2.17 on 2026-09-24 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_companynamechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTrigger',
            fields=[
                ('notification_trigger_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_key', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=20)),
                ('notification_trigger_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(db_column='alert_id', on_delete=django.db.models.deletion.PROTECT, related_name='notification_triggers', to='core.mailalertdtl')),
            ],
            options={
                'db_table': 'notification_trigger',
                'constraints': [models.UniqueConstraint(fields=('entity_key', 'action'), name='uniq_notification_trigger_entity_action')],
            },
        ),
    ]
