# Generated by Django 5.2.17 on 2026-09-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_notificationtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='attachment_names',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
