# Generated by Django 5.2.17 on 2026-09-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_emaillog_attachment_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShortcut',
            fields=[
                ('user_shortcut_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login_id', models.CharField(db_index=True, max_length=20)),
                ('path', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('cr_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_user_shortcut',
                'ordering': ['sort_order', 'user_shortcut_id'],
                'unique_together': {('user_login_id', 'path')},
            },
        ),
    ]
