# Generated by Django 5.2.17 on 2026-09-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_usershortcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherQhseAction',
            fields=[
                ('other_qhse_action_id', models.AutoField(primary_key=True, serialize=False)),
                ('icr_no', models.CharField(max_length=15)),
                ('other_qhse_action_dt', models.DateField()),
                ('action_recommended', models.CharField(max_length=500)),
                ('action_taken', models.CharField(blank=True, max_length=250, null=True)),
                ('action_party', models.CharField(max_length=100)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_dt', models.DateField(blank=True, null=True)),
                ('action_status', models.CharField(max_length=2)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('qhse_category', models.ForeignKey(db_column='qhse_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='other_qhse_actions', to='core.mstqhsecategory')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='other_qhse_actions', to='core.mstrig')),
            ],
            options={
                'db_table': 'other_qhse_action',
            },
        ),
    ]
