# Generated by Django 5.2.17 on 2026-09-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_otherqhseaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardcard',
            name='resp_dept',
            field=models.ForeignKey(db_column='resp_dept_id', on_delete=django.db.models.deletion.PROTECT, related_name='hazard_cards', to='core.mstvesseldept'),
        ),
    ]
