# Generated by Django 5.2.17 on 2026-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_fix_hazard_card_resp_dept_fk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drillingdtl',
            constraint=models.UniqueConstraint(fields=('rig', 'drilling_dtl_dt'), name='uniq_drilling_dtl_rig_date'),
        ),
    ]
