# Generated by Django 5.2.17 on 2026-09-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_drilling_dtl_unique_rig_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstHseMeeting',
            fields=[
                ('hse_meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('hse_meeting_type', models.CharField(max_length=50)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_hse_meeting',
            },
        ),
        migrations.AddField(
            model_name='mstincidenttype',
            name='show_on_mis_hse_report',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.CreateModel(
            name='MisMonthlyHseReturnsHdr',
            fields=[
                ('monthly_hse_returns_hdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_no', models.CharField(max_length=20)),
                ('report_month', models.DateField()),
                ('lti_free_days', models.IntegerField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('cost_centre', models.ForeignKey(blank=True, db_column='cost_centre_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_hse_returns', to='core.mstcostcentre')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='mis_hse_returns', to='core.mstrig')),
            ],
            options={
                'db_table': 'mis_monthly_hse_returns_hdr',
            },
        ),
        migrations.CreateModel(
            name='MisMonthlyHseEnvironment',
            fields=[
                ('monthly_hse_environment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('consumable', models.ForeignKey(db_column='hse_consumable_id', on_delete=django.db.models.deletion.PROTECT, to='core.msthseconsumable')),
                ('hdr', models.ForeignKey(db_column='monthly_hse_returns_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='environment_rows', to='core.mismonthlyhsereturnshdr')),
            ],
            options={
                'db_table': 'mis_monthly_hse_environment',
            },
        ),
        migrations.CreateModel(
            name='MisMonthlyHseActivities',
            fields=[
                ('monthly_hse_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_activities', models.IntegerField(blank=True, null=True)),
                ('seros_emp_count', models.IntegerField(blank=True, null=True)),
                ('contractor_count', models.IntegerField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(db_column='hse_activity_id', on_delete=django.db.models.deletion.PROTECT, to='core.msthseactivity')),
                ('hdr', models.ForeignKey(db_column='monthly_hse_returns_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='hse_activities', to='core.mismonthlyhsereturnshdr')),
            ],
            options={
                'db_table': 'mis_monthly_hse_activities',
            },
        ),
        migrations.CreateModel(
            name='MstHseManhoursParty',
            fields=[
                ('hse_manhours_party_id', models.AutoField(primary_key=True, serialize=False)),
                ('hse_manhours_party_name', models.CharField(max_length=50)),
                ('hse_manhours_party_type', models.CharField(choices=[('SEROS', 'SEROS'), ('TP', 'Third Party')], max_length=5)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('cost_centre_type', models.ForeignKey(blank=True, db_column='cost_centre_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hse_manhours_parties', to='core.mstcostcentretype')),
            ],
            options={
                'db_table': 'mst_hse_manhours_party',
            },
        ),
        migrations.CreateModel(
            name='MisMonthlyHseManhours',
            fields=[
                ('monthly_hse_manhours_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_personnel', models.IntegerField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hdr', models.ForeignKey(db_column='monthly_hse_returns_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='manhours', to='core.mismonthlyhsereturnshdr')),
                ('party', models.ForeignKey(db_column='hse_manhours_party_id', on_delete=django.db.models.deletion.PROTECT, to='core.msthsemanhoursparty')),
            ],
            options={
                'db_table': 'mis_monthly_hse_manhours',
            },
        ),
        migrations.CreateModel(
            name='MisMonthlyHseMeetings',
            fields=[
                ('monthly_hse_meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_meetings', models.IntegerField(blank=True, null=True)),
                ('total_seros_employees', models.IntegerField(blank=True, null=True)),
                ('total_contractors', models.IntegerField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hdr', models.ForeignKey(db_column='monthly_hse_returns_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.mismonthlyhsereturnshdr')),
                ('meeting', models.ForeignKey(db_column='hse_meeting_id', on_delete=django.db.models.deletion.PROTECT, to='core.msthsemeeting')),
            ],
            options={
                'db_table': 'mis_monthly_hse_meetings',
            },
        ),
        migrations.AddConstraint(
            model_name='mismonthlyhsereturnshdr',
            constraint=models.UniqueConstraint(fields=('rig', 'report_month'), name='uniq_mis_hse_return_rig_month'),
        ),
        migrations.AddConstraint(
            model_name='mismonthlyhseenvironment',
            constraint=models.UniqueConstraint(fields=('hdr', 'consumable'), name='uniq_mis_hse_environment_hdr_consumable'),
        ),
        migrations.AddConstraint(
            model_name='mismonthlyhseactivities',
            constraint=models.UniqueConstraint(fields=('hdr', 'activity'), name='uniq_mis_hse_activities_hdr_activity'),
        ),
        migrations.AddConstraint(
            model_name='mismonthlyhsemanhours',
            constraint=models.UniqueConstraint(fields=('hdr', 'party'), name='uniq_mis_hse_manhours_hdr_party'),
        ),
        migrations.AddConstraint(
            model_name='mismonthlyhsemeetings',
            constraint=models.UniqueConstraint(fields=('hdr', 'meeting'), name='uniq_mis_hse_meetings_hdr_meeting'),
        ),
    ]
