# Generated by Django 5.2.17 on 2026-09-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_msthsemeeting_mstincidenttype_show_on_mis_hse_report_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mismonthlyhsereturnshdr',
            name='uniq_mis_hse_return_rig_month',
        ),
        migrations.AlterField(
            model_name='mismonthlyhsereturnshdr',
            name='cost_centre',
            field=models.ForeignKey(db_column='cost_centre_id', on_delete=django.db.models.deletion.PROTECT, related_name='mis_hse_returns', to='core.mstcostcentre'),
        ),
        migrations.AlterField(
            model_name='mismonthlyhsereturnshdr',
            name='rig',
            field=models.ForeignKey(blank=True, db_column='rig_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_hse_returns', to='core.mstrig'),
        ),
        migrations.AddConstraint(
            model_name='mismonthlyhsereturnshdr',
            constraint=models.UniqueConstraint(fields=('cost_centre', 'report_month'), name='uniq_mis_hse_return_cost_centre_month'),
        ),
    ]
