# Generated by Django 5.2.17 on 2026-10-01 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_mismonthlyhsereturnshdr_uniq_mis_hse_return_rig_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstHseDrill',
            fields=[
                ('hse_drill_id', models.AutoField(primary_key=True, serialize=False)),
                ('hse_drill_name', models.CharField(max_length=100)),
                ('hse_drill_frequency', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annual')], max_length=1)),
                ('hse_drill_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('rig_type', models.ForeignKey(blank=True, db_column='rig_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hse_drills', to='core.mstrigtype')),
            ],
            options={
                'db_table': 'mst_hse_drill',
            },
        ),
        migrations.CreateModel(
            name='HseDrillRecordHdr',
            fields=[
                ('drill_record_hdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill_record_sr_no', models.IntegerField()),
                ('drill_record_no', models.CharField(max_length=20)),
                ('drill_dt', models.DateTimeField()),
                ('drill_location', models.CharField(max_length=20)),
                ('head_count', models.IntegerField()),
                ('initial_response_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('no_of_participants', models.IntegerField()),
                ('control_room_on_shore', models.CharField(max_length=1)),
                ('fire_team_1_size', models.IntegerField(blank=True, null=True)),
                ('fire_team_1_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fire_team_2_size', models.IntegerField(blank=True, null=True)),
                ('fire_team_2_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('stretcher_team_size', models.IntegerField(blank=True, null=True)),
                ('maintenance_team_size', models.IntegerField(blank=True, null=True)),
                ('snr_team_size', models.IntegerField(blank=True, null=True)),
                ('snr_team_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('drill_muster', models.DecimalField(decimal_places=2, max_digits=4)),
                ('abandon_muster_offshore', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_time_of_drill', models.DecimalField(decimal_places=2, max_digits=4)),
                ('approved_by_companyman', models.CharField(blank=True, max_length=20, null=True)),
                ('revision_value', models.IntegerField(default=0)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('approved_by_oim_fs_emp', models.ForeignKey(db_column='approved_by_oim_fs_emp_id', on_delete=django.db.models.deletion.PROTECT, related_name='drills_approved', to='core.mstemployee')),
                ('initiated_by_fs_emp_1', models.ForeignKey(db_column='initiated_by_fs_emp_id_1', on_delete=django.db.models.deletion.PROTECT, related_name='drills_initiated_as_1', to='core.mstemployee')),
                ('initiated_by_fs_emp_2', models.ForeignKey(blank=True, db_column='initiated_by_fs_emp_id_2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drills_initiated_as_2', to='core.mstemployee')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='hse_drill_records', to='core.mstrig')),
                ('hse_drill_1', models.ForeignKey(db_column='hse_drill_id_1', on_delete=django.db.models.deletion.PROTECT, related_name='drill_records_as_1', to='core.msthsedrill')),
                ('hse_drill_2', models.ForeignKey(blank=True, db_column='hse_drill_id_2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drill_records_as_2', to='core.msthsedrill')),
            ],
            options={
                'db_table': 'hse_drill_record_hdr',
                'constraints': [models.UniqueConstraint(fields=('rig', 'drill_record_sr_no'), name='uniq_hse_drill_record_rig_sr_no')],
            },
        ),
    ]
