# Generated by Django 5.2.17 on 2026-10-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_msthsedrill_hsedrillrecordhdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='HseDrillRecordCorrectiveAction',
            fields=[
                ('drill_rec_corrective_action_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill_rec_corrective_action_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hdr', models.ForeignKey(db_column='drill_record_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='core.hsedrillrecordhdr')),
            ],
            options={
                'db_table': 'hse_drill_record_corrective_action',
            },
        ),
        migrations.CreateModel(
            name='HseDrillRecordEvent',
            fields=[
                ('drill_rec_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill_rec_event_time', models.DateTimeField()),
                ('drill_rec_event_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hdr', models.ForeignKey(db_column='drill_record_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.hsedrillrecordhdr')),
            ],
            options={
                'db_table': 'hse_drill_record_event',
                'ordering': ['drill_rec_event_time'],
            },
        ),
        migrations.CreateModel(
            name='HseDrillRecordImprovement',
            fields=[
                ('drill_rec_improvement_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill_rec_improvement_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hdr', models.ForeignKey(db_column='drill_record_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='core.hsedrillrecordhdr')),
            ],
            options={
                'db_table': 'hse_drill_record_improvement',
            },
        ),
        migrations.CreateModel(
            name='HseDrillRecordObservation',
            fields=[
                ('drill_rec_observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill_rec_observation_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hdr', models.ForeignKey(db_column='drill_record_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.hsedrillrecordhdr')),
            ],
            options={
                'db_table': 'hse_drill_record_observation',
            },
        ),
        migrations.CreateModel(
            name='HseDrillRecordPhotoUpload',
            fields=[
                ('drill_rec_photo_upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill_rec_photo_upload_path', models.CharField(max_length=50)),
                ('drill_rec_photo_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hdr', models.ForeignKey(db_column='drill_record_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='photo_uploads', to='core.hsedrillrecordhdr')),
            ],
            options={
                'db_table': 'hse_drill_record_photo_upload',
            },
        ),
    ]
