# Generated by Django 5.2.17 on 2026-10-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_hsedrillrecordcorrectiveaction_hsedrillrecordevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msthsedrill',
            name='hse_drill_frequency',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('B', 'Bi-Annually'), ('A', 'Annually')], max_length=1),
        ),
        migrations.CreateModel(
            name='HseWeeklyDrillHdr',
            fields=[
                ('hse_weekly_drill_hdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill_year', models.DateField()),
                ('drill_week', models.PositiveSmallIntegerField()),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='hse_weekly_drills', to='core.mstrig')),
            ],
            options={
                'db_table': 'hse_weekly_drill_hdr',
            },
        ),
        migrations.CreateModel(
            name='HseWeeklyDrillDtl',
            fields=[
                ('hse_weekly_drill_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill_conducted_dt', models.DateField()),
                ('drill_last_conducted_dt', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hse_drill', models.ForeignKey(db_column='hse_drill_id', on_delete=django.db.models.deletion.PROTECT, related_name='weekly_drill_dtls', to='core.msthsedrill')),
                ('hdr', models.ForeignKey(db_column='hse_weekly_drill_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='dtls', to='core.hseweeklydrillhdr')),
            ],
            options={
                'db_table': 'hse_weekly_drill_dtl',
            },
        ),
        migrations.AddConstraint(
            model_name='hseweeklydrillhdr',
            constraint=models.UniqueConstraint(fields=('rig', 'drill_year', 'drill_week'), name='uq_hse_weekly_drill_rig_year_week'),
        ),
        migrations.AddConstraint(
            model_name='hseweeklydrilldtl',
            constraint=models.UniqueConstraint(fields=('hdr', 'hse_drill'), name='uq_hse_weekly_drill_dtl_hdr_drill'),
        ),
    ]
