# Generated by Django 5.2.17 on 2026-10-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_hseweeklydrillhdr_hseweeklydrilldtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadingIndicatorsHdr',
            fields=[
                ('report_no', models.CharField(max_length=12, unique=True)),
                ('period', models.DateField()),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('leading_indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstcompany')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstrig')),
            ],
            options={
                'db_table': 'leading_indicators_hdr',
            },
        ),
        migrations.CreateModel(
            name='LeadingIndicatorsDtl',
            fields=[
                ('total_sessions', models.PositiveSmallIntegerField(default=0)),
                ('no_of_persons', models.PositiveSmallIntegerField(default=0)),
                ('total_duration', models.PositiveSmallIntegerField(default=0)),
                ('duration_type', models.CharField(blank=True, max_length=1, null=True)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('leading_indicator_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_subtype', models.ForeignKey(blank=True, db_column='indicator_subtype_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstindicatorsubtype')),
                ('indicator_type', models.ForeignKey(db_column='indicator_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstindicatortype')),
                ('workgroup', models.ForeignKey(db_column='workgroup_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstworkgroup')),
                ('hdr', models.ForeignKey(db_column='leading_indicator_id', on_delete=django.db.models.deletion.CASCADE, related_name='dtls', to='core.leadingindicatorshdr')),
            ],
            options={
                'db_table': 'leading_indicators_dtl',
            },
        ),
    ]
