# Generated by Django 5.2.17 on 2026-10-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_leadingindicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadingindicatorsdtl',
            name='no_of_persons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leadingindicatorsdtl',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leadingindicatorsdtl',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
