# Generated by Django 5.2.17 on 2026-10-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_laggingindicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='HseTrainingGroupHdr',
            fields=[
                ('training_group_hdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_group_hdr_name', models.CharField(max_length=30)),
                ('training_group_hdr_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hse_training_group_hdr',
            },
        ),
        migrations.CreateModel(
            name='FsCatgToRankMapping',
            fields=[
                ('fs_catg_to_rank_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='rank_mappings', to='core.mstfscategory')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='category_mappings', to='core.mstrank')),
                ('vessel_dept', models.ForeignKey(db_column='vessel_dept_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstvesseldept')),
            ],
            options={
                'db_table': 'fs_catg_to_rank_mapping',
            },
        ),
        migrations.CreateModel(
            name='HseTrainingGroupDtl',
            fields=[
                ('training_group_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('mandatory_training', models.CharField(blank=True, default='', max_length=1)),
                ('training_group_dtl_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstfscategory')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='training_group_dtls', to='core.mstrank')),
                ('hdr', models.ForeignKey(db_column='training_group_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='dtls', to='core.hsetraininggrouphdr')),
            ],
            options={
                'db_table': 'hse_training_group_dtl',
            },
        ),
    ]
