# Generated by Django 5.2.17 on 2026-10-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_training_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='HseTrainingOrgHdr',
            fields=[
                ('training_org_hdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_org_name', models.CharField(max_length=75)),
                ('training_org_address', models.CharField(max_length=100)),
                ('contact_person_1', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_no_1', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_person_2', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_no_2', models.CharField(blank=True, max_length=15, null=True)),
                ('training_org_email', models.CharField(blank=True, max_length=30, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, related_name='training_orgs', to='core.mstcountry')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, related_name='training_orgs', to='core.mstlocation')),
            ],
            options={
                'db_table': 'hse_training_org_hdr',
            },
        ),
        migrations.CreateModel(
            name='HseTrainingOrgDtl',
            fields=[
                ('training_org_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_fname', models.CharField(max_length=25)),
                ('trainer_mname', models.CharField(blank=True, max_length=25, null=True)),
                ('trainer_lname', models.CharField(max_length=25)),
                ('trainer_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('trainer_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('trainer_email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('hdr', models.ForeignKey(db_column='training_org_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='dtls', to='core.hsetrainingorghdr')),
            ],
            options={
                'db_table': 'hse_training_org_dtl',
            },
        ),
    ]
