# Generated by Django 5.2.17 on 2026-10-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_training_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertToRankMapping',
            fields=[
                ('cert_to_rank_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_to_rank_mapping_active', models.CharField(default='Y', max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('cert', models.ForeignKey(db_column='cert_id', on_delete=django.db.models.deletion.PROTECT, related_name='rank_mappings', to='core.mstcert')),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstfscategory')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, related_name='cert_mappings', to='core.mstrank')),
            ],
            options={
                'db_table': 'cert_to_rank_mapping',
            },
        ),
    ]
