# Generated by Django 5.2.17 on 2026-10-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_fs_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='HseTrainingLogHdr',
            fields=[
                ('training_log_hdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_location', models.CharField(max_length=50)),
                ('training_dt', models.DateField()),
                ('training_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=8)),
                ('course_duration', models.PositiveSmallIntegerField()),
                ('assessment_conducted', models.CharField(max_length=1)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('cert', models.ForeignKey(db_column='cert_id', on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to='core.mstcert')),
                ('rig', models.ForeignKey(db_column='rig_id', on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to='core.mstrig')),
                ('training_org', models.ForeignKey(db_column='training_org_hdr_id', on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to='core.hsetrainingorghdr')),
                ('training_org_dtl', models.ForeignKey(db_column='training_org_dtl_id', on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to='core.hsetrainingorgdtl')),
            ],
            options={
                'db_table': 'hse_training_log_hdr',
            },
        ),
        migrations.CreateModel(
            name='HseTrainingLogDtl',
            fields=[
                ('training_log_dtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_party', models.CharField(max_length=15)),
                ('trainee_fname', models.CharField(max_length=20)),
                ('trainee_mname', models.CharField(blank=True, max_length=20, null=True)),
                ('trainee_lname', models.CharField(max_length=25)),
                ('trainee_designation', models.CharField(max_length=35)),
                ('trainee_department', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=75)),
                ('certificate_issued', models.CharField(max_length=1)),
                ('certificate_no', models.CharField(blank=True, max_length=25, null=True)),
                ('certificate_dt', models.DateField(blank=True, null=True)),
                ('cert_valid_upto', models.DateField(blank=True, null=True)),
                ('certificate_path', models.CharField(blank=True, max_length=150, null=True)),
                ('cr_user_id', models.IntegerField()),
                ('cr_dt', models.DateTimeField()),
                ('mod_user_id', models.IntegerField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('fs_category', models.ForeignKey(db_column='fs_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mstfscategory')),
                ('fs_emp', models.ForeignKey(blank=True, db_column='fs_emp_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to='core.mstfsemployee')),
                ('hdr', models.ForeignKey(db_column='training_log_hdr_id', on_delete=django.db.models.deletion.CASCADE, related_name='dtls', to='core.hsetrainingloghdr')),
            ],
            options={
                'db_table': 'hse_training_log_dtl',
            },
        ),
    ]
